import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";



export const metadata: Metadata = {
  title: "公子請記帳",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
